blueprint:
  name: SmartThings Button Setup
  description: Setup actions for three functions of a SmartThings button with "press", "double press", and "hold"
  domain: automation

  input:
    button_id:
      name: Button
      description: The button device to configure
      selector:
        device:
          filter:
            - integration: smartthings
    press_action:
      name: Press Action
      description: Action to perform on "press" event
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to perform on "double press" event
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Action to perform on "hold" event
      default: []
      selector:
        action: {}

variables:
  button_id: !input button_id
  press_action: !input press_action
  double_press_action: !input double_press_action
  hold_action: !input hold_action

trigger:
  - platform: event
    event_type: smartthings.button
    event_data:
      component_id: main
      device_id: !input button_id
      value: pushed
    id: pushed
  - platform: event
    event_type: smartthings.button
    event_data:
      component_id: main
      device_id: !input button_id
      value: double
    id: double
  - platform: event
    event_type: smartthings.button
    event_data:
      component_id: main
      device_id: !input button_id
      value: held
    id: held

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - held
        sequence: !input hold_action
      - conditions:
          - condition: trigger
            id:
              - double
        sequence: !input double_press_action
    default: !input press_action

mode: single
